export const LOAD_MOVIES = 'LOAD_MOVIES';
export const LOAD_MOVIES_SUCCESS = 'LOAD_MOVIES_SUCCESS';
export const LOAD_MOVIES_ERROR = 'LOAD_MOVIES_ERROR';
export const LOAD_DETAILS = 'LOAD_DETAILS';
export const LOAD_DETAILS_SUCCESS = 'LOAD_DETAILS_SUCCESS';
export const LOAD_DETAILS_ERROR = 'LOAD_DETAILS_ERROR';
export const CHANGE_KEYWORD = 'CHANGE_KEYWORD';